# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-03 06:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('barcode', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('internal_code', models.TextField(blank=True)),
                ('last_update_date', models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0))),
            ],
        ),
    ]
