# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0002_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
    ]
