# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-03 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventorycheck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClerkMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'permissions': (('send_clerk_message', 'allows sending message to clerks'),),
            },
        ),
    ]
