'''
Copyright (C) Lee Fong Int'l Group, Inc, Macau - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * Template generated by Django 1.10.4
 * Maintained by Victor Hu <weichunghu@gmail.com>, Jan.-Aug. 2017
'''
__author__ = "Victor Hu"
__copyright__ = "Copyright (C) 2017 Lee Fong Int'l Group, Inc, Macau"
__license__ = "Lee Fong Int'l Group"

ADV_IMAGE_BASE = 'media/adv_images/'
DEFAULT_IMAGE = ADV_IMAGE_BASE + 'None/no-img.jpg'

